spring:
  application:
    name: itoken-zipkin
  boot:  # spring boot admin 健康检测地址配置
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

management:
  metrics: # 服务链路追踪 2.8版本之前没有这个配置 2.10以后要添加这个配置
    web:
      server:
        auto-time-requests: false
  endpoint: #健康检测配置 每个项目中都应该配置一个健康检查
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health , info #health(信息监控),info(健康健康)  健康检查参数 *代表所有的


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

