spring:
  application:
    name: itoken-service-admin
  zipkin: #zipkin 服务追踪依赖
    base-url: http://localhost:9411
  boot:  # spring boot admin 健康检查地址配置
    admin:
      client:
        url: http://localhost:8084
  datasource: # 数据源配置
    druid:
      url: jdbc:mysql://192.168.254.136:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501

mybatis: #mybatis 配置
  type-aliases-package: com.gyf.itoken.service.admin.domain   # domain领域模型   #实体类的存放路径，如：com.gyf.hello.spring.boot.entity
  mapper-locations: classpath:mapper/*.xml      #classpath:mapper/*.xml 是在resources目录下（不用新建）

management:
  endpoint: #健康检测配置 每个项目中都应该配置一个健康检查
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health ,info #health(信息监控),info(健康健康)  健康检查参数 *代表所有的

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


