spring:
  application:
    name: itoken-zuul
  zipkin: #zipkin 服务追踪依赖
    base-url: http://localhost:9411
  boot:  # spring boot admin 健康检查地址配置
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8769

management:
  endpoint: #健康检测配置 每个项目中都应该配置一个健康检查
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health , info #health(信息监控),info(健康健康)  健康检查参数 *代表所有的


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul: #网关配置
  routes: #路由
    api-a: #自己起名
      path: /api/a/**   # **全目录匹配
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign