spring:
  application:
    name: itoken-config
  cloud: #云端配置依赖
    config:
      label: master  #分支
      server:
        git:
          uri: https://github.com/itokenProjects/itoken-config.git  #github地址
          search-paths: respo  #路径
          username: wzk-ai
          password: wzk199458
  zipkin: #zipkin 服务追踪依赖
    base-url: http://localhost:9411
  boot:  # spring boot admin 健康检测地址配置
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

management:
  endpoint: #健康检测配置 每个项目中都应该配置一个健康检查
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health , info #health(信息监控),info(健康健康)  健康检查参数 *代表所有的


eureka:
  client:
    serviceUrl:
      defaultZone: http://106.54.218.126:8761/eureka/